# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

# trigger by curl -H "Accept: application/vnd.github+json" -H "Authorization: token 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" --request POST --data '{"event_type": "on-demand-test","client_payload": {"application": "demo","revision": "revision", "auther": "auther", "details": "sha123456"}}' https://api.github.com/repos/node-real/gh-action-test/dispatches
name: go # caller

on:
  repository_dispatch:
    types: [test-center]

jobs:
  checkout:
    runs-on: [self-hosted,qa-infra-k8s]
    steps:
    - uses: actions/checkout@v3
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
    - name: Dump steps context
      run: echo '${{ toJSON(steps) }}'
    - name: Dump runner context
      run: echo '${{ toJSON(runner) }}'
    - name: Dump strategy context
      run: echo '${{ toJSON(strategy) }}'
    - name: Dump matrix context
      run: echo '${{ toJSON(matrix) }}'
